# Generated by Django 4.2.2 on 2023-06-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
